#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Ratcheting gate on cross-test UpdateQueue leaks.
#
# A test that returns with callbacks still queued hands them to the next test.
# HelixTestFixture's ctor drains the queue, notifying subjects that died with the
# leaking test — a SIGSEGV in lv_subject_notify that lands on whichever test
# constructed a fixture next, so it moves with shard composition and looks like a
# bug in an innocent test. That is prestonbrown/helixscreen#1146.
#
# The isolation listener discards leftover callbacks between tests and reports
# each one as "[ISOLATION-LEAK] ... Producers: <tag>". Discarding makes the crash
# unreachable, but the underlying defect — a queue_update site capturing raw this
# with no lifetime guard (docs/devel/THREADING.md §2) — is still there. This gate
# stops the population growing while it gets worked down (#1166).
#
# This is a RATCHET, not a wall. The baseline freezes today's count so the debt can
# only shrink: a new leak fails the build, and fixing one lowers the number.
#
# The count is NOT shard-independent, so the baseline is only meaningful against a
# fixed invocation. Measured on the same build: 305 leaks unsharded, 286 across 8
# shards. The listener does discard after every test, but several producers are
# process singletons (AmsState::set_active_tool_port_present and friends) that only
# queue when a value actually CHANGES — and whether it changes depends on what
# earlier tests in the same process left in that singleton. Splitting the run
# changes which tests share a process, so it changes the count.
#
# The baseline below is therefore pinned to ONE canonical invocation:
#
#     ./build/bin/helix-tests "~[.] ~[slow]" 2>&1 | tee run.log
#
# The 2>&1 is REQUIRED, not incidental. The listener reports via fprintf(stderr)
# while Catch2's summary goes to stdout, so a log missing either stream is rejected:
# the gate demands a Catch2 run summary before it will believe a low leak count.
# Without that, a stdout-only log reads as "0 leaks" and passes forever.
#
# Do not compare a baseline taken this way against summed shard logs; the numbers
# are not the same quantity. This is also why the gate runs in nightly rather than
# on every PR — build.yml shards across $(nproc), which varies by runner.
#
# Usage:
#   check_update_queue_leaks.py run.log                  # count
#   cat run.log | check_update_queue_leaks.py -          # or from stdin
#   check_update_queue_leaks.py --max-allowed 305 run.log  # ratcheting baseline
#   check_update_queue_leaks.py --list run.log           # every leaking test
#   check_update_queue_leaks.py --by-producer run.log    # group by queueing tag

import argparse
import collections
import re
import sys

# Matches the listener's report in tests/unit/test_isolation_listener.cpp.
LEAK_RE = re.compile(
    r'\[ISOLATION-LEAK\] test "(?P<test>.*)" left (?P<count>\d+) queued UpdateQueue '
    r'callback\(s\); discarded\. Producers: (?P<producers>.*)$'
)


# Catch2's end-of-run summary. Its presence proves the log really is a completed
# test run, which is what makes "zero leaks" trustworthy rather than just silent.
RUN_MARKER_RE = re.compile(r'All tests passed|test cases:\s*\d+|assertions:\s*\d+')


def parse(streams):
    """Return (leaks, total_callbacks, saw_run). leaks is [(test, count, producers)]."""
    leaks = []
    total_callbacks = 0
    saw_run = False
    for stream in streams:
        for line in stream:
            if not saw_run and RUN_MARKER_RE.search(line):
                saw_run = True
            m = LEAK_RE.search(line)
            if not m:
                continue
            count = int(m.group('count'))
            leaks.append((m.group('test'), count, m.group('producers').strip()))
            total_callbacks += count
    return leaks, total_callbacks, saw_run


BASELINE_HEADER = (
    '# Tests known to return with UpdateQueue callbacks still queued (#1166).\n'
    '# One Catch2 test-case name per line. Generated by:\n'
    '#   ./build/bin/helix-tests "~[.] ~[slow]" 2>&1 | tee run.log\n'
    '#   scripts/check_update_queue_leaks.py --write-baseline <this file> run.log\n'
    '#\n'
    '# A test NOT listed here that leaks fails the build. This is a set, not a\n'
    '# count, because the count is timing-dependent (measured 305/305/302 across\n'
    '# three identical unsharded runs) while the membership is stable.\n'
    '# The list may SHRINK as leaks are fixed; it must not grow.\n'
)


def read_baseline(path):
    try:
        with open(path) as fh:
            return {
                line.strip()
                for line in fh
                if line.strip() and not line.lstrip().startswith('#')
            }
    except OSError as e:
        print(f'❌ UpdateQueue leaks: cannot read baseline {path}: {e}')
        sys.exit(2)


def open_streams(paths):
    if not paths or paths == ['-']:
        return [sys.stdin]
    handles = []
    for p in paths:
        try:
            handles.append(open(p, 'r', errors='replace'))
        except OSError as e:
            print(f'❌ UpdateQueue leaks: cannot read {p}: {e}')
            sys.exit(2)
    return handles


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument('logs', nargs='*', help='Test output logs (or - for stdin)')
    ap.add_argument(
        '--max-allowed',
        type=int,
        default=None,
        help='Pass if leaking tests <= N (ratcheting baseline). Omit to fail on any leak.',
    )
    ap.add_argument(
        '--baseline',
        metavar='FILE',
        help='Known-leaker set. Fail only on a leaking test NOT listed. Preferred over '
        '--max-allowed: the count flaps run to run, the set does not.',
    )
    ap.add_argument(
        '--write-baseline',
        metavar='FILE',
        help='Write the leaking tests in these logs to FILE and exit.',
    )
    ap.add_argument('--list', action='store_true', help='Print every leaking test')
    ap.add_argument(
        '--by-producer', action='store_true', help='Group leaks by queueing tag'
    )
    ap.add_argument('--summary', action='store_true', help='Counts only')
    args = ap.parse_args()

    streams = open_streams(args.logs)
    leaks, total_callbacks, saw_run = parse(streams)
    for s in streams:
        if s is not sys.stdin:
            s.close()

    total = len(leaks)

    # Absence of evidence is not evidence of absence. A log with no reports is only
    # trustworthy if it also shows a completed run — otherwise it is a broken
    # invocation (wrong path, crashed early, or stderr not captured, since the
    # listener reports via fprintf(stderr)) and would silently "pass" forever.
    if not saw_run:
        print('❌ UpdateQueue leaks: no Catch2 run summary found in the log(s).')
        print('   This does not look like a completed test run. Capture stderr:')
        print('     ./build/bin/helix-tests "~[.] ~[slow]" 2>&1 | tee run.log')
        return 2

    if args.list:
        for test, count, producers in sorted(leaks):
            print(f'{count:4d}  {test}  [{producers}]')
        print()

    if args.by_producer:
        by_tag = collections.Counter()
        for _, _, producers in leaks:
            for tag in producers.split(','):
                by_tag[re.sub(r' x\d+$', '', tag.strip())] += 1
        for tag, n in by_tag.most_common():
            print(f'{n:4d}  {tag}')
        print()

    detail = f'{total} leaking test(s), {total_callbacks} callback(s)'
    names = {t for t, _, _ in leaks}

    if args.write_baseline:
        with open(args.write_baseline, 'w') as fh:
            fh.write(BASELINE_HEADER)
            for n in sorted(names):
                fh.write(n + '\n')
        print(f'✅ Wrote {len(names)} known leaker(s) to {args.write_baseline}')
        return 0

    if args.baseline:
        known = read_baseline(args.baseline)
        new = sorted(names - known)
        gone = sorted(known - names)
        if new:
            print(f'❌ UpdateQueue leaks: {len(new)} test(s) not in the baseline set.')
            for n in new:
                print(f'     {n}')
            print('   A test returned with callbacks queued; the next fixture drain would')
            print('   notify subjects that died with it. Drain in the owning fixture dtor,')
            print('   while its subjects are still alive.')
            print('   See prestonbrown/helixscreen#1166 and docs/devel/THREADING.md §2.')
            return 1
        # Absences are expected: ~7 known leakers flap with thread timing, so a
        # short "gone" list is noise, not progress. Only a sustained drop is worth
        # rewriting the baseline for, hence this reports without failing.
        print(f'✅ UpdateQueue leaks: {detail}; no new leakers ({len(known)} known).')
        if gone:
            print(f'   {len(gone)} baseline entr(ies) did not leak this run.')
            print('   If that holds across runs, regenerate with --write-baseline.')
        return 0

    if args.max_allowed is None:
        if total:
            print(f'❌ UpdateQueue leaks: {detail}.')
            print('   Drain in the owning fixture dtor, while its subjects are alive.')
            return 1
        print('✅ UpdateQueue leaks: none.')
        return 0

    limit = args.max_allowed
    if total > limit:
        print(f'❌ UpdateQueue leaks: {detail} exceeds baseline ({limit}).')
        print('   A test returned with callbacks queued; the next fixture drain would')
        print('   notify subjects that died with it. Drain in the owning fixture dtor.')
        print('   Run: python3 scripts/check_update_queue_leaks.py --list <logs>')
        print('   See prestonbrown/helixscreen#1166 and docs/devel/THREADING.md §2.')
        return 1
    if total < limit:
        print(f'✅ UpdateQueue leaks: {detail} (baseline {limit} — ratchet the baseline down)')
        return 0
    print(f'✅ UpdateQueue leaks: {detail} == baseline ({limit})')
    return 0



if __name__ == '__main__':
    sys.exit(main())
